/* eslint-disable require-jsdoc */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import { GetStaticProps } from "next";
import Layout from '../components/common/layout';
import { fetchEntries } from '../components/util/contentfulFetch';
/**
 * Home: The Landing page of the web app
 * @return {JSX.Element} The JSX Code for the Home Page
 */

type Props = {
  contentfulHome: any;
};

export default function Index({ contentfulHome }: Props) {

  console.log(contentfulHome);
  return (
    <div className={styles.container}>
      <Head>
        <title>Antik Tugra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout logo={contentfulHome.fields.logoWithText}>
      </Layout>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  // const productsApiHit = await fetch(
  //   `https://${process.env.NEXT_PUBLIC_SHOPIFY_USERNAME}:${process.env.NEXT_PUBLIC_SHOPIFY_PASSWORD}@${process.env.NEXT_PUBLIC_SHOPIFY_STORE_NAME}.myshopify.com/admin/api/2021-04/products.json`
  // );
  // const productsData = await productsApiHit.json();

  const contentfulHome = await fetchEntries('2DwnMy8uQ4Y39tufTxw5UO')

  return {
    props: {
      contentfulHome,
    },
    revalidate: 300, // Time in seconds before regenerating
  };
};
